-- Run this in Supabase Dashboard > SQL Editor.
create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  album text,
  cover_url text,
  audio_url text not null,
  created_at timestamptz not null default now()
);

alter table public.songs enable row level security;

create policy "Public can read songs"
on public.songs for select
using (true);

create policy "Public can add songs"
on public.songs for insert
with check (true);

create policy "Public can edit songs"
on public.songs for update
using (true)
with check (true);

create policy "Public can delete songs"
on public.songs for delete
using (true);
